"""Output formatting for different formats."""

import json
from typing import Dict, Any, List
from src.analyzer import CodeIssue


class OutputFormatter:
    """Format review results in different output formats."""

    def to_json(self, results: Dict[str, Any]) -> str:
        """Convert results to JSON format."""
        # Convert CodeIssue objects to dicts
        output = results.copy()
        if "issues" in output:
            output["issues"] = [
                {
                    "severity": issue.severity,
                    "type": issue.type,
                    "message": issue.message,
                    "file": issue.file,
                    "line_number": issue.line_number,
                    "suggestion": issue.suggestion,
                }
                if isinstance(issue, CodeIssue)
                else issue
                for issue in output["issues"]
            ]
        
        return json.dumps(output, indent=2)

    def to_markdown(self, results: Dict[str, Any], path: str) -> str:
        """Convert results to Markdown format."""
        lines = []
        
        # Header
        lines.append(f"# AI Code Review: {path}")
        lines.append("")
        
        # Summary
        stats = results.get("stats", {})
        lines.append("## Summary")
        lines.append("")
        lines.append(f"- **Files Analyzed:** {stats.get('files_analyzed', 0)}")
        lines.append(f"- **Lines of Code:** {stats.get('lines_of_code', 0)}")
        lines.append(f"- **Issues Found:** {len(results.get('issues', []))}")
        lines.append("")
        
        # Issues
        issues = results.get("issues", [])
        if issues:
            lines.append("## Issues")
            lines.append("")
            
            # Group by severity
            by_severity = {"critical": [], "high": [], "medium": [], "low": []}
            for issue in issues:
                severity = issue.severity if isinstance(issue, CodeIssue) else issue.get("severity", "low")
                if severity in by_severity:
                    by_severity[severity].append(issue)
            
            # Output by severity
            for severity in ["critical", "high", "medium", "low"]:
                severity_issues = by_severity[severity]
                if not severity_issues:
                    continue
                
                emoji = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢"}.get(severity, "⚪")
                lines.append(f"### {emoji} {severity.upper()}")
                lines.append("")
                
                for issue in severity_issues:
                    if isinstance(issue, CodeIssue):
                        file = issue.file
                        line = issue.line_number
                        msg = issue.message
                        suggestion = issue.suggestion
                    else:
                        file = issue.get("file", "unknown")
                        line = issue.get("line_number", 0)
                        msg = issue.get("message", "No description")
                        suggestion = issue.get("suggestion")
                    
                    lines.append(f"- **{file}:{line}** - {msg}")
                    if suggestion:
                        lines.append(f"  - 💡 {suggestion}")
                    lines.append("")
        else:
            lines.append("## ✅ No Issues Found")
            lines.append("")
        
        # Footer
        lines.append("---")
        lines.append("*Generated by AI Code Reviewer*")
        
        return "\n".join(lines)

    def to_text(self, results: Dict[str, Any]) -> str:
        """Convert results to plain text format."""
        lines = []
        
        stats = results.get("stats", {})
        lines.append("=" * 60)
        lines.append("AI CODE REVIEW RESULTS")
        lines.append("=" * 60)
        lines.append("")
        lines.append(f"Files Analyzed: {stats.get('files_analyzed', 0)}")
        lines.append(f"Lines of Code: {stats.get('lines_of_code', 0)}")
        lines.append(f"Issues Found: {len(results.get('issues', []))}")
        lines.append("")
        
        issues = results.get("issues", [])
        if issues:
            for issue in issues:
                if isinstance(issue, CodeIssue):
                    severity = issue.severity
                    file = issue.file
                    line = issue.line_number
                    msg = issue.message
                else:
                    severity = issue.get("severity", "unknown")
                    file = issue.get("file", "unknown")
                    line = issue.get("line_number", 0)
                    msg = issue.get("message", "No description")
                
                lines.append(f"[{severity.upper()}] {file}:{line}")
                lines.append(f"  {msg}")
                lines.append("")
        
        return "\n".join(lines)