"""Formatter for different output formats."""

import json
from typing import Dict, Any, List
from datetime import datetime


class Formatter:
    """Base formatter class."""
    
    def format(self, data: Dict[str, Any]) -> str:
        """Format data to string."""
        raise NotImplementedError


class TextFormatter(Formatter):
    """Plain text formatter."""
    
    def format(self, data: Dict[str, Any]) -> str:
        """Format as plain text."""
        lines = []
        lines.append("=" * 60)
        lines.append("CODE REVIEW REPORT")
        lines.append("=" * 60)
        lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append("")
        
        # Summary
        issues = data.get('issues', {})
        lines.append("SUMMARY")
        lines.append("-" * 40)
        
        for category, items in issues.items():
            lines.append(f"{category.upper()}: {len(items)}")
        
        lines.append("")
        
        # Details
        for category, items in issues.items():
            if items:
                lines.append(f"\n{category.upper()} ISSUES:")
                lines.append("-" * 40)
                for item in items:
                    msg = item.get('message', 'No message')
                    line = item.get('line_number', '?')
                    lines.append(f"  Line {line}: {msg}")
        
        lines.append("")
        lines.append("=" * 60)
        
        return '\n'.join(lines)


class JSONFormatter(Formatter):
    """JSON formatter."""
    
    def format(self, data: Dict[str, Any]) -> str:
        """Format as JSON."""
        return json.dumps(data, indent=2, default=str)


class MarkdownFormatter(Formatter):
    """Markdown formatter."""
    
    def format(self, data: Dict[str, Any]) -> str:
        """Format as Markdown."""
        lines = []
        
        # Title
        lines.append("# Code Review Report")
        lines.append("")
        lines.append(f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*")
        lines.append("")
        
        # Summary
        issues = data.get('issues', {})
        lines.append("## Summary")
        lines.append("")
        
        total = sum(len(items) for items in issues.values())
        lines.append(f"**Total Issues:** {total}")
        lines.append("")
        
        for category, items in issues.items():
            lines.append(f"- **{category.capitalize()}:** {len(items)}")
        
        lines.append("")
        
        # Issues
        for category, items in issues.items():
            if items:
                lines.append(f"## {category.capitalize()} Issues")
                lines.append("")
                for item in items:
                    msg = item.get('message', 'No message')
                    line = item.get('line_number', 'N/A')
                    file_path = item.get('file_path', 'N/A')
                    lines.append(f"### Line {line} - {file_path}")
                    lines.append(f"```\n{msg}\n```")
                    lines.append("")
        
        lines.append("")
        lines.append("*Report generated by AI Code Reviewer*")
        
        return '\n'.join(lines)


class HTMLFormatter(Formatter):
    """HTML formatter."""
    
    def format(self, data: Dict[str, Any]) -> str:
        """Format as HTML."""
        html = ['<!DOCTYPE html>']
        html.append('<html><head>')
        html.append('<title>Code Review Report</title>')
        html.append('<style>')
        html.append('body { font-family: Arial, sans-serif; margin: 20px; }')
        html.append('.critical { color: red; }')
        html.append('.warning { color: orange; }')
        html.append('.info { color: blue; }')
        html.append('</style></head><body>')
        
        html.append('<h1>Code Review Report</h1>')
        html.append(f'<p>Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>')
        
        issues = data.get('issues', {})
        for category, items in issues.items():
            css_class = category.lower()
            html.append(f'<h2 class="{css_class}">{category.capitalize()} Issues ({len(items)})</h2>')
            for item in items:
                msg = item.get('message', 'No message')
                line = item.get('line_number', 'N/A')
                html.append(f'<p><strong>Line {line}:</strong> {msg}</p>')
        
        html.append('</body></html>')
        
        return '\n'.join(html)


def get_formatter(format_type: str) -> Formatter:
    """Get formatter by type."""
    formatters = {
        'text': TextFormatter,
        'json': JSONFormatter,
        'markdown': MarkdownFormatter,
        'html': HTMLFormatter
    }
    
    formatter_class = formatters.get(format_type.lower(), TextFormatter)
    return formatter_class()