"""Report generation module for code review results.

This module provides various report generation capabilities including:
- Summary reports
- Detailed reports
- GitHub comment format
- Email-friendly format
"""

import json
from typing import Dict, Any, List, Optional
from datetime import datetime
from pathlib import Path
from src.models import CodeIssue


class ReportGenerator:
    """Generate various types of reports from analysis results."""
    
    def __init__(self):
        self.timestamp = datetime.now()
    
    def generate_summary_report(self, results: Dict[str, Any]) -> str:
        """Generate a summary report.
        
        Args:
            results: Analysis results dictionary
            
        Returns:
            Formatted summary report string
        """
        stats = results.get("stats", {})
        issues = results.get("issues", [])
        
        # Count by severity
        by_severity = {"critical": 0, "high": 0, "medium": 0, "low": 0}
        for issue in issues:
            severity = issue.severity if isinstance(issue, CodeIssue) else issue.get("severity", "low")
            if severity in by_severity:
                by_severity[severity] += 1
        
        # Count by type
        by_type = {}
        for issue in issues:
            issue_type = issue.type if isinstance(issue, CodeIssue) else issue.get("type", "unknown")
            by_type[issue_type] = by_type.get(issue_type, 0) + 1
        
        report = []
        report.append("=" * 60)
        report.append("CODE REVIEW SUMMARY")
        report.append("=" * 60)
        report.append(f"\nGenerated: {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}")
        report.append(f"\nFiles Analyzed: {stats.get('files_analyzed', 0)}")
        report.append(f"Lines of Code: {stats.get('lines_of_code', 0)}")
        
        report.append("\n" + "-" * 40)
        report.append("ISSUES BY SEVERITY")
        report.append("-" * 40)
        
        for severity in ["critical", "high", "medium", "low"]:
            count = by_severity[severity]
            emoji = self._get_severity_emoji(severity)
            report.append(f"  {emoji} {severity.upper()}: {count}")
        
        report.append("\n" + "-" * 40)
        report.append("ISSUES BY TYPE")
        report.append("-" * 40)
        
        for issue_type, count in sorted(by_type.items(), key=lambda x: -x[1]):
            report.append(f"  • {issue_type}: {count}")
        
        report.append("\n" + "=" * 60)
        
        return "\n".join(report)
    
    def generate_github_comment(self, results: Dict[str, Any]) -> str:
        """Generate a GitHub-friendly comment.
        
        Args:
            results: Analysis results dictionary
            
        Returns:
            Markdown-formatted comment for GitHub
        """
        issues = results.get("issues", [])
        stats = results.get("stats", {})
        
        comment = []
        comment.append("## 🤖 AI Code Review")
        comment.append("")
        
        # Summary
        comment.append("### Summary")
        comment.append("")
        comment.append(f"| Metric | Value |")
        comment.append(f"|--------|-------|")
        comment.append(f"| Files Analyzed | {stats.get('files_analyzed', 0)} |")
        comment.append(f"| Lines of Code | {stats.get('lines_of_code', 0)} |")
        comment.append(f"| Issues Found | {len(issues)} |")
        comment.append("")
        
        if not issues:
            comment.append("✅ **No issues found!**")
            return "\n".join(comment)
        
        # Group by severity
        by_severity = self._group_issues(issues)
        
        for severity in ["critical", "high", "medium", "low"]:
            severity_issues = by_severity.get(severity, [])
            if not severity_issues:
                continue
            
            emoji = self._get_severity_emoji(severity)
            comment.append(f"### {emoji} {severity.upper()} ({len(severity_issues)})")
            comment.append("")
            
            for issue in severity_issues[:10]:  # Limit to 10 per severity
                if isinstance(issue, CodeIssue):
                    file = Path(issue.file).name
                    line = issue.line_number
                    msg = issue.message
                else:
                    file = Path(issue.get("file", "")).name
                    line = issue.get("line_number", 0)
                    msg = issue.get("message", "")
                
                comment.append(f"- **{file}:{line}** - {msg}")
            
            if len(severity_issues) > 10:
                comment.append(f"- ... and {len(severity_issues) - 10} more")
            
            comment.append("")
        
        comment.append("---")
        comment.append("*Generated by AI Code Reviewer*")
        
        return "\n".join(comment)
    
    def generate_email_report(self, results: Dict[str, Any], title: str = "Code Review") -> str:
        """Generate an email-friendly report.
        
        Args:
            results: Analysis results dictionary
            title: Report title
            
        Returns:
            Plain text email-formatted report
        """
        issues = results.get("issues", [])
        stats = results.get("stats", {})
        
        email = []
        email.append(f"{title}")
        email.append("=" * len(title))
        email.append(f"\nDate: {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}")
        email.append(f"Files Analyzed: {stats.get('files_analyzed', 0)}")
        email.append(f"Lines of Code: {stats.get('lines_of_code', 0)}")
        email.append(f"Issues Found: {len(issues)}")
        
        if not issues:
            email.append("\nNo issues were found in this review.")
            return "\n".join(email)
        
        # Group by severity
        by_severity = self._group_issues(issues)
        
        for severity in ["critical", "high", "medium", "low"]:
            severity_issues = by_severity.get(severity, [])
            if not severity_issues:
                continue
            
            emoji = self._get_severity_emoji(severity)
            email.append(f"\n{emoji} {severity.upper()} ISSUES ({len(severity_issues)})")
            email.append("-" * 40)
            
            for issue in severity_issues:
                if isinstance(issue, CodeIssue):
                    file = issue.file
                    line = issue.line_number
                    msg = issue.message
                    suggestion = issue.suggestion
                else:
                    file = issue.get("file", "")
                    line = issue.get("line_number", 0)
                    msg = issue.get("message", "")
                    suggestion = issue.get("suggestion", "")
                
                email.append(f"\n  [{file}:{line}]")
                email.append(f"  {msg}")
                if suggestion:
                    email.append(f"  Suggestion: {suggestion}")
            
            email.append("")
        
        return "\n".join(email)
    
    def generate_html_report(self, results: Dict[str, Any], title: str = "Code Review Report") -> str:
        """Generate a standalone HTML report.
        
        Args:
            results: Analysis results dictionary
            title: Report title
            
        Returns:
            Full HTML document
        """
        issues = results.get("issues", [])
        stats = results.get("stats", {})
        
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 20px;
        }}
        .summary {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 15px;
            margin-bottom: 30px;
        }}
        .stat-card {{
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            text-align: center;
        }}
        .stat-value {{
            font-size: 28px;
            font-weight: bold;
            color: #667eea;
        }}
        .stat-label {{
            color: #666;
            font-size: 14px;
        }}
        .severity-section {{
            background: white;
            margin-bottom: 20px;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .severity-header {{
            padding: 15px 20px;
            color: white;
            font-weight: bold;
        }}
        .severity-critical {{ background: #dc3545; }}
        .severity-high {{ background: #fd7e14; }}
        .severity-medium {{ background: #ffc107; color: #333; }}
        .severity-low {{ background: #28a745; }}
        .issue-list {{
            padding: 0;
            margin: 0;
            list-style: none;
        }}
        .issue-item {{
            padding: 15px 20px;
            border-bottom: 1px solid #eee;
        }}
        .issue-item:last-child {{
            border-bottom: none;
        }}
        .issue-file {{
            color: #666;
            font-size: 12px;
            font-family: monospace;
        }}
        .issue-message {{
            margin: 5px 0;
            color: #333;
        }}
        .issue-suggestion {{
            font-size: 13px;
            color: #666;
            font-style: italic;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🤖 {title}</h1>
        <p>Generated: {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}</p>
    </div>
    
    <div class="summary">
        <div class="stat-card">
            <div class="stat-value">{stats.get('files_analyzed', 0)}</div>
            <div class="stat-label">Files Analyzed</div>
        </div>
        <div class="stat-card">
            <div class="stat-value">{stats.get('lines_of_code', 0)}</div>
            <div class="stat-label">Lines of Code</div>
        </div>
        <div class="stat-card">
            <div class="stat-value">{len(issues)}</div>
            <div class="stat-label">Issues Found</div>
        </div>
    </div>
"""
        
        by_severity = self._group_issues(issues)
        
        for severity in ["critical", "high", "medium", "low"]:
            severity_issues = by_severity.get(severity, [])
            if not severity_issues:
                continue
            
            html += f'<div class="severity-section">\n'
            html += f'<div class="severity-header severity-{severity}">'
            html += f'{self._get_severity_emoji(severity)} {severity.upper()} ({len(severity_issues)})'
            html += '</div>\n<ul class="issue-list">\n'
            
            for issue in severity_issues:
                if isinstance(issue, CodeIssue):
                    file = issue.file
                    line = issue.line_number
                    msg = issue.message
                    suggestion = issue.suggestion
                else:
                    file = issue.get("file", "")
                    line = issue.get("line_number", 0)
                    msg = issue.get("message", "")
                    suggestion = issue.get("suggestion", "")
                
                html += f'<li class="issue-item">\n'
                html += f'<div class="issue-file">{file}:{line}</div>\n'
                html += f'<div class="issue-message">{msg}</div>\n'
                if suggestion:
                    html += f'<div class="issue-suggestion">💡 {suggestion}</div>\n'
                html += '</li>\n'
            
            html += '</ul>\n</div>\n'
        
        html += """</body>
</html>"""
        
        return html
    
    def _group_issues(self, issues: List[Any]) -> Dict[str, List[Any]]:
        """Group issues by severity."""
        grouped = {"critical": [], "high": [], "medium": [], "low": []}
        
        for issue in issues:
            severity = "low"
            if isinstance(issue, CodeIssue):
                severity = issue.severity
            elif isinstance(issue, dict):
                severity = issue.get("severity", "low")
            
            if severity in grouped:
                grouped[severity].append(issue)
            else:
                grouped["low"].append(issue)
        
        return grouped
    
    def _get_severity_emoji(self, severity: str) -> str:
        """Get emoji for severity level."""
        emoji_map = {
            "critical": "🔴",
            "high": "🟠",
            "medium": "🟡",
            "low": "🟢",
        }
        return emoji_map.get(severity, "⚪")
